[build]
publish = "public"
command = "hugo"

[build.environment]
HUGO_VERSION = "0.49"

[context.production.environment]
HUGO_BASEURL = "https://www.avthart.com/"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --enableGitInfo"

[context.split1.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
